blank_issues_enabled: true
contact_links:
  - name: IndopenSource Discussions
    url: https://github.com/orgs/IndopenSource/discussions
    about: Use discussions for broad ideas, questions, and community planning.
